# Generated by Django 5.1.15 on 2026-08-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_delivery_address_order_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
