# Generated by Django 5.1.15 on 2026-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dish_is_available_alter_favorite_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Через запятую: лосось, сыр, рис', verbose_name='Состав'),
        ),
    ]
